import type { Data_System } from "@sigureya/rpgtypes";
export const system: Data_System = {
  advanced: {
    gameId: 18121146,
    screenWidth: 816,
    screenHeight: 624,
    uiAreaWidth: 816,
    uiAreaHeight: 624,
    numberFontFilename: "mplus-2p-bold-sub.woff",
    fallbackFonts: "Verdana, sans-serif",
    fontSize: 26,
    mainFontFilename: "mplus-1m-regular.woff",
    windowOpacity: 192,
    screenScale: 1,
  },
  airship: {
    bgm: { name: "Ship3", pan: 0, pitch: 100, volume: 90 },
    characterIndex: 3,
    characterName: "Vehicle",
    startMapId: 29,
    startX: 6,
    startY: 15,
  },
  armorTypes: [
    "",
    "一般防具",
    "魔法防具",
    "軽装防具",
    "重装防具",
    "小型盾",
    "大型盾",
  ],
  attackMotions: [
    { type: 0, weaponImageId: 0 },
    { type: 1, weaponImageId: 1 },
    { type: 1, weaponImageId: 2 },
    { type: 1, weaponImageId: 3 },
    { type: 1, weaponImageId: 4 },
    { type: 1, weaponImageId: 5 },
    { type: 1, weaponImageId: 6 },
    { type: 2, weaponImageId: 7 },
    { type: 2, weaponImageId: 8 },
    { type: 2, weaponImageId: 9 },
    { type: 0, weaponImageId: 10 },
    { type: 0, weaponImageId: 11 },
    { type: 0, weaponImageId: 12 },
  ],
  battleBgm: { name: "Battle1", pan: 0, pitch: 100, volume: 90 },
  battleback1Name: "GrassMaze",
  battleback2Name: "GrassMaze",
  // battlerHue: 0,
  battlerName: "Hi_monster",
  // battleSystem: 0,
  boat: {
    bgm: { name: "Ship1", pan: 0, pitch: 100, volume: 90 },
    characterIndex: 0,
    characterName: "Vehicle",
    startMapId: 0,
    startX: 0,
    startY: 0,
  },
  currencyUnit: "EL",
  defeatMe: { name: "Defeat1", pan: 0, pitch: 100, volume: 90 },
  editMapId: 4,
  elements: ["", "物理", "炎", "氷", "雷", "水", "土", "風", "光", "闇"],
  equipTypes: ["", "武器", "盾", "頭", "身体", "装飾品"],
  gameTitle: "プラグイン開発",
  gameoverMe: { name: "Gameover1", pan: 0, pitch: 100, volume: 90 },
  // itemCategories: [true, true, true, true],
  // locale: "ja_JP",
  // magicSkills: [1],
  // menuCommands: [true, true, true, true, true, true],
  optAutosave: true,
  optDisplayTp: true,
  optDrawTitle: true,
  optExtraExp: false,
  optFloorDeath: false,
  optFollowers: true,
  optKeyItemsNumber: false,
  optSideView: true,
  optSlipDeath: false,
  optTransparent: false,
  // partyMembers: [1, 6],
  ship: {
    bgm: { name: "Ship2", pan: 0, pitch: 100, volume: 90 },
    characterIndex: 1,
    characterName: "Vehicle",
    startMapId: 29,
    startX: 5,
    startY: 3,
  },
  skillTypes: [
    "",
    "魔法",
    "必殺技",
    "剣技",
    "道具使用",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  sounds: [
    { name: "Cursor3", pan: 0, pitch: 100, volume: 90 },
    { name: "Decision2", pan: 0, pitch: 100, volume: 90 },
    { name: "Cancel2", pan: 0, pitch: 100, volume: 90 },
    { name: "Buzzer1", pan: 0, pitch: 100, volume: 90 },
    { name: "Equip1", pan: 0, pitch: 100, volume: 90 },
    { name: "Save2", pan: 0, pitch: 100, volume: 90 },
    { name: "Load2", pan: 0, pitch: 100, volume: 90 },
    { name: "Battle1", pan: 0, pitch: 100, volume: 90 },
    { name: "Run", pan: 0, pitch: 100, volume: 90 },
    { name: "Attack3", pan: 0, pitch: 100, volume: 90 },
    { name: "Damage4", pan: 0, pitch: 100, volume: 90 },
    { name: "Collapse1", pan: 0, pitch: 100, volume: 90 },
    { name: "Collapse2", pan: 0, pitch: 100, volume: 90 },
    { name: "Collapse3", pan: 0, pitch: 100, volume: 90 },
    { name: "Damage5", pan: 0, pitch: 100, volume: 90 },
    { name: "Collapse4", pan: 0, pitch: 100, volume: 90 },
    { name: "Recovery", pan: 0, pitch: 100, volume: 90 },
    { name: "Miss", pan: 0, pitch: 100, volume: 90 },
    { name: "Evasion1", pan: 0, pitch: 100, volume: 90 },
    { name: "Evasion2", pan: 0, pitch: 100, volume: 90 },
    { name: "Reflection", pan: 0, pitch: 100, volume: 90 },
    { name: "Shop1", pan: 0, pitch: 100, volume: 90 },
    { name: "Item3", pan: 0, pitch: 100, volume: 90 },
    { name: "Item3", pan: 0, pitch: 100, volume: 90 },
  ],
  startMapId: 4,
  startX: 5,
  startY: 2,
  switches: [
    "",
    "",
    "",
    "",
    "SKIP:トリアコンタン",
    "",
    "セーブ読み込み検知",
    "街中モード",
    "何かのスイッチ",
    "ログ全ボタン無効化",
    "ログ記録有効化",
    "ログボタン有効化",
    "途中セーブ有効化",
    "途中ロード有効化",
    "並列ダミー起動",
    "時間切れ",
    "アイテム非表示",
    "バックアップ1記録済み",
    "アイテム入手無効化",
    "簡単スイッチ用",
    "コモンイベント27起動",
    "コモン28並列起動",
    "既読スキップモード",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  terms: {
    basic: [
      "レベル",
      "Lv",
      "ＨＰ",
      "HP",
      "ＭＰ",
      "MP",
      "ＴＰ",
      "TP",
      "経験値",
      "EXP",
    ],
    commands: [
      "fight",
      "escape",
      "攻撃",
      "防御",
      "アイテム",
      "スキル",
      "装備",
      "ステータス",
      "並び替え",
      "セーブ",
      "ゲーム終了",
      "オプション",
      "武器",
      "防具",
      "大事なもの",
      "装備",
      "最強装備",
      "全て外す",
      "ニューゲーム",
      "コンティニュー",
      "ショップ",
      "タイトルへ",
      "やめる",
      "メニュー",
      "購入する",
      "売却する",
    ],
    params: [
      "最大ＨＰ",
      "最大ＭＰ",
      "攻撃力",
      "防御力",
      "魔法力",
      "魔法防御",
      "敏捷性",
      "運",
      "命中率",
      "回避率",
    ],
    messages: {
      alwaysDash: "常時ダッシュ",
      commandRemember: "コマンド記憶",
      touchUI: "タッチUI",
      bgmVolume: "BGM 音量",
      bgsVolume: "BGS 音量",
      meVolume: "ME 音量",
      seVolume: "SE 音量",
      possession: "持っている数",
      expTotal: "現在の%1",
      expNext: "次の%1まで",
      saveMessage: "どのファイルにセーブしますか？",
      loadMessage: "どのファイルをロードしますか？",
      file: "ファイル",
      autosave: "オートセーブ",
      partyName: "%1たち",
      emerge: "%1が出現！",
      preemptive: "%1は先手を取った！",
      surprise: "%1は不意をつかれた！",
      escapeStart: "%1は逃げ出した！",
      escapeFailure: "しかし逃げることはできなかった！",
      victory: "%1の勝利！",
      defeat: "%1は戦いに敗れた。",
      obtainExp: "%1 の%2を獲得！",
      obtainGold: "お金を %1\\G 手に入れた！",
      obtainItem: "%1を手に入れた！",
      levelUp: "%1は%2 %3 に上がった！",
      obtainSkill: "%1を覚えた！",
      useItem: "%1は%2を使った！",
      criticalToEnemy: "会心の一撃！！",
      criticalToActor: "痛恨の一撃！！",
      actorDamage: "%1は %2 のダメージを受けた！",
      actorRecovery: "%1の%2が %3 回復した！",
      actorGain: "%1の%2が %3 増えた！",
      actorLoss: "%1の%2が %3 減った！",
      actorDrain: "%1は%2を %3 奪われた！",
      actorNoDamage: "%1はダメージを受けていない！",
      actorNoHit: "ミス！　%1はダメージを受けていない！",
      enemyDamage: "%1に %2 のダメージを与えた！",
      enemyRecovery: "%1の%2が %3 回復した！",
      enemyGain: "%1の%2が %3 増えた！",
      enemyLoss: "%1の%2が %3 減った！",
      enemyDrain: "%1の%2を %3 奪った！",
      enemyNoDamage: "%1にダメージを与えられない！",
      enemyNoHit: "ミス！　%1にダメージを与えられない！",
      evasion: "%1は攻撃をかわした！",
      magicEvasion: "%1は魔法を打ち消した！",
      magicReflection: "%1は魔法を跳ね返した！",
      counterAttack: "%1の反撃！",
      substitute: "%1が%2をかばった！",
      buffAdd: "%1の%2が上がった！",
      debuffAdd: "%1の%2が下がった！",
      buffRemove: "%1の%2が元に戻った！",
      actionFailure: "%1には効かなかった！",
    },
  },
  testBattlers: [
    { actorId: 1, level: 99, equips: [2, 1, 2, 3, 7] },
    { actorId: 5, level: 1, equips: [7, 0, 0, 20, 0] },
    { actorId: 0, level: 1, equips: [7, 0, 65, 21, 0] },
    { actorId: 0, level: 1, equips: [7, 0, 0, 20, 0] },
  ],
  testTroopId: 10,
  title1Name: "Town2",
  title2Name: "",
  titleBgm: { name: "Theme4", pan: 0, pitch: 100, volume: 90 },
  //  titleCommandWindow: { background: 0, offsetX: 0, offsetY: 0 },
  variables: [
    "",
    "セーブ立ち絵(デフォ)",
    "冒険者ポイント",
    "アイテム値段",
    "",
    "",
    "",
    "",
    "",
    "",
    "数値入力用(文字列禁止)",
    "一時記録1",
    "一時記録2",
    "一時記録3",
    "一時記録4",
    "一時記録B",
    "お金書き込み",
    "アクターID",
    "一時記録変数",
    "選択結果保存",
    "ループ用カーソル書き込み",
    "",
    "",
    "",
    "アイテム生成ID",
    "アイテム生成X",
    "アイテム生成Y",
    "アイテム生成個数",
    "採取回数",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "開いている宝箱",
    "閉じている宝箱",
    "全ての宝箱",
    "",
    "アイテム入手(個数)",
    "アイテム個数カウント",
    "アイテム名称",
    "アイテムID",
    "",
    "MapID",
    "MapX",
    "MapY",
    "復帰用：向き",
    "ストレージ指定",
    "",
    "",
    "",
    "",
    "",
    "",
    "最終アクション",
    "セーブ画面立ち絵",
    "セーブ画面文章",
    "ウィンドウスキンID",
    "最大HP",
    "最大MP",
    "攻撃力",
    "防御力",
    "魔法攻撃力",
    "魔法防御力",
    "素早さ",
    "運",
    "名前",
    "装備種別テキスト",
    "説明文",
    "装備値段",
    "アイテムアイコン",
    "アイテム個数",
    "次のレベルの経験値",
    "次まで必要な経験値",
    "現在の経験値",
    "",
    "",
    "セーブ結果確認",
    "消費MP",
    "消費TP",
    "取得TP",
    "スキルタイプ",
    "アニメーションID",
    "属性番号",
    "属性名称",
    "スキル名称",
    "直前のレベル",
    "現在のレベル",
    "",
    "",
    "",
    "",
    "",
    "",
    "ジョイピクチャX",
    "ジョイピクチャY",
    "ジョイスティックRX",
    "ジョイスティックRY",
    "ボス制御1",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  versionId: 76455767,
  victoryMe: { name: "Victory1", pan: 0, pitch: 100, volume: 90 },
  weaponTypes: [
    "",
    "短剣",
    "剣",
    "フレイル",
    "斧",
    "ムチ",
    "杖",
    "弓",
    "クロスボウ",
    "銃",
    "爪",
    "グローブ",
    "槍",
  ],
  windowTone: [-255, -255, -255, 0],
  local: "",
};
